### ISSUE TITLE
When will OmniZeroCouple be available?

### ISSUE THREAD

**Issue by fuchao01** [okaris/omni-zero#11]
When will OmniZeroCouple be available?

**Comment by okaris** [comment]
I’m doing the final cleanup and adding the UI examples now. Hoping to release in a week.

**Comment by mertyagmur** [comment]
> I’m doing the final cleanup and adding the UI examples now. Hoping to release in a week.

Any updates on this?

**Comment by andupotorac** [comment]
Also looking forward to try this out.

**Comment by okaris** [comment]
@fuchao01 @mertyagmur @andupotorac it's here https://github.com/okaris/omni-zero-couples thanks for your patience!
