### ISSUE TITLE
Commercial usage restriction

### ISSUE THREAD

**Issue by jadechip** [okaris/omni-zero#12]
How can this allow for commercial usage when it is dependent on Insightface's antelopev2 which have a clear non-commercial license?

**Comment by okaris** [comment]
The license in this repository governs the code within the repository itself and does not extend to any models or third-party components used. It is the user’s responsibility to verify and comply with the licensing terms of any third-party models, such as Insightface’s Antelopev2, before using them in commercial applications. This is an industry standard practice, where users are expected to ensure compliance with external licensing requirements.
