### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [okaris/omni-zero#2]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by TechnologyClassroom** [comment]
In case you didn't know, GPLv2 has many flaws which were patched in GPLv3 and AGPLv3. With its flaws, GPLv2 is better than no license.

**Comment by okaris** [comment]
Thank you @TechnologyClassroom 🙏🏻
