### ISSUE TITLE
Missing modules from requirements.txt

### ISSUE THREAD

**Issue by mpalo** [okaris/omni-zero#5]
After installing pip install -r requirements.txt and running demo.py:

ModuleNotFoundError: No module named 'onnxruntime'
and
ModuleNotFoundError: No module named 'hf_transfer'

**Comment by merolaika** [comment]
I had the same problem and I reached the solution with the following steps:

pip install onnxruntime-gpu
pip install hf_transfer
python.exe -m pip install --upgrade pip

**Comment by okaris** [comment]
@mpalo @merolaika Thanks for reporting 🙏🏻
