### ISSUE TITLE
Clarification on Base Image and Composition_Image in Replicate Demo

### ISSUE THREAD

**Issue by karthikg-09** [okaris/omni-zero#8]
What is the difference between the base image and the Composition_Image in the replicate demo? I see that the base image has the main control over the pose. Could you please remove the second image and make just one image for composition?

**Comment by okaris** [comment]
When you use the base image it starts the diffusion process from that image so it is closer to the base/composition image. I'll push an update removing the requirement from both so you can choose one and the image will be used for both

**Comment by okaris** [comment]
Update the replicate model, new model version id is `sha256:1a6dcacf62f387316745e91928dec9d59412b6d0518647fdb0f52e6f40b6a46c`
